### ISSUE TITLE
Error write file Preferences

### ISSUE THREAD

**Issue by huongtran** [grezzled/AntiAdLimit#1]
Hello, Thanks for work, when I using lib, I got error when write to Preferences because path is invalid, Could you please check and fix help me ?
    java.lang.IllegalArgumentException: File ca-app-pub-3940256099942544/6300978111.xml contains a path separator
        at android.app.ContextImpl.makeFilename(ContextImpl.java:2657)
        at android.app.ContextImpl.getSharedPreferencesPath(ContextImpl.java:787)
        at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:439)
        at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:178)
        at anti.ad.limit.PrefUtils.init(PrefUtils.java:50)
        at anti.ad.limit.JSONPullService.onHandleIntent(JSONPullService.java:94)
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:78)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by huongtran** [comment]
@grezzled Please check help me.
